### ISSUE TITLE
Please add screenshots of the app to the readme

### ISSUE THREAD

**Issue by mainrs** [T8RIN/CookHelper#2]
Having to install an APK to get a glimps on how the app looks and works is not a good idea. You can use sth. like fastlane to automate screenshots.

**Comment by T8RIN** [comment]
> Having to install an APK to get a glimps on how the app looks and works is not a good idea. You can use sth. like fastlane to automate screenshots.

Thx for your comment, i will add them soon

**Comment by T8RIN** [comment]
Added screenshots
